COUNTRY_CURRENCIES: dict[str, str] = {
    "AD": "EUR", "AE": "AED", "AF": "AFN", "AL": "ALL", "AM": "AMD",
    "AO": "AOA", "AR": "ARS", "AT": "EUR", "AU": "AUD", "AZ": "AZN",
    "BA": "BAM", "BD": "BDT", "BE": "EUR", "BG": "BGN", "BH": "BHD",
    "BR": "BRL", "BY": "BYN", "CA": "CAD", "CH": "CHF", "CL": "CLP",
    "CN": "CNY", "CO": "COP", "CR": "CRC", "CU": "CUP", "CY": "EUR",
    "CZ": "CZK", "DE": "EUR", "DK": "DKK", "DZ": "DZD", "EC": "USD",
    "EE": "EUR", "EG": "EGP", "ES": "EUR", "FI": "EUR", "FR": "EUR",
    "GB": "GBP", "GE": "GEL", "GH": "GHS", "GR": "EUR", "HK": "HKD",
    "HR": "EUR", "HU": "HUF", "ID": "IDR", "IE": "EUR", "IL": "ILS",
    "IN": "INR", "IQ": "IQD", "IR": "IRR", "IS": "ISK", "IT": "EUR",
    "JO": "JOD", "JP": "JPY", "KE": "KES", "KG": "KGS", "KH": "KHR",
    "KR": "KRW", "KW": "KWD", "KZ": "KZT", "LB": "LBP", "LK": "LKR",
    "LT": "EUR", "LU": "EUR", "LV": "EUR", "MA": "MAD", "MD": "MDL",
    "ME": "EUR", "MK": "MKD", "MM": "MMK", "MN": "MNT", "MT": "EUR",
    "MX": "MXN", "MY": "MYR", "NG": "NGN", "NL": "EUR", "NO": "NOK",
    "NP": "NPR", "NZ": "NZD", "OM": "OMR", "PA": "USD", "PE": "PEN",
    "PH": "PHP", "PK": "PKR", "PL": "PLN", "PT": "EUR", "QA": "QAR",
    "RO": "RON", "RS": "RSD", "RU": "RUB", "SA": "SAR", "SE": "SEK",
    "SG": "SGD", "SI": "EUR", "SK": "EUR", "TH": "THB", "TJ": "TJS",
    "TM": "TMT", "TN": "TND", "TR": "TRY", "TW": "TWD", "UA": "UAH",
    "US": "USD", "UY": "UYU", "UZ": "UZS", "VE": "VES", "VN": "VND",
    "ZA": "ZAR",
}
